namespace Vipi.Infrastructure.Persistence;

/// <summary>
/// Dove vivono le chiavi Data Protection (antiforgery, cookie di autenticazione, state OIDC) e con quale DDL
/// nasce la loro tabella.
///
/// <para><b>Perché è una decisione e non un dettaglio.</b> Il key-ring predefinito è una cartella sul disco.
/// Su un filesystem effimero — il container di Render, un processo riavviato da systemd su una macchina
/// riprovisionata — le chiavi si perdono a ogni riavvio, e il sintomo non parla di chiavi: gli utenti si
/// ritrovano sloggati e i form rispondono «antiforgery token non valido». Dove il database è persistente e il
/// disco no, il key-ring va nel database.</para>
///
/// <para><b>Perché la logica sta qui e non nell'host.</b> È l'unico punto in cui si decide, per provider, se
/// il key-ring vive nel DB — e la risposta sbagliata è silenziosa: si degrada al file-store e non lo dice
/// nessuno. Tenerla in una funzione pura la rende verificabile su entrambi i target, invece che solo
/// guidando l'app dopo un riavvio.</para>
///
/// <para>Il consumatore è <c>VipiDataProtection</c> in <c>Vipi.Host</c>, che di suo fa solo il wiring.</para>
/// </summary>
public static class DataProtectionSchema
{
    /// <summary>
    /// Nome della tabella. <b>Le maiuscole contano</b>: su Linux <c>lower_case_table_names</c> è 0, quindi
    /// <c>dataprotectionkeys</c> e <c>DataProtectionKeys</c> sono due tabelle diverse e EF cerca la seconda
    /// (convenzione: il nome del <c>DbSet</c>). Su Windows il problema non si vede.
    /// </summary>
    public const string TableName = "DataProtectionKeys";

    /// <summary>
    /// Se il key-ring di questo provider deve vivere nel database.
    ///
    /// <para><see cref="PersistenceProvider.Sqlite"/> è lo sviluppo su una macchina sola, dove il file-store
    /// predefinito è adeguato e non aggiunge tabelle al DB di lavoro. Gli altri due sono deploy dove il
    /// processo può ripartire su un disco che non ricorda niente.</para>
    /// </summary>
    public static bool UsesDatabaseKeyRing(PersistenceProvider provider)
        => provider is PersistenceProvider.Postgres or PersistenceProvider.MySql;

    /// <summary>
    /// DDL idempotente della tabella delle chiavi, nella forma attesa da
    /// <c>EntityFrameworkCoreXmlRepository</c> (<c>Id</c> identità, <c>FriendlyName</c>, <c>Xml</c>).
    ///
    /// <para>⚠️ <b>Non</b> si usa <c>EnsureCreated()</c>: verifica l'esistenza del <i>database</i>, non della
    /// tabella. Su un database che esiste già — sempre, visto che è quello del modulo — non crea niente e il
    /// primo accesso muore con «relation does not exist». È già costato una sessione su Postgres.</para>
    /// </summary>
    public static string CreateTableSql(PersistenceProvider provider) => provider switch
    {
        PersistenceProvider.Postgres => $"""
            CREATE TABLE IF NOT EXISTS "{TableName}" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FriendlyName" text NULL,
                "Xml" text NULL
            );
            """,

        // La collation è la stessa delle altre 163 colonne stringa (MySqlCollation): non perché il confronto
        // di un FriendlyName sia critico, ma perché una tabella che eredita il default del database sarebbe
        // l'unica a comportarsi diversamente dal resto dello schema — una singolarità da spiegare ogni volta.
        PersistenceProvider.MySql => $"""
            CREATE TABLE IF NOT EXISTS `{TableName}` (
                `Id` int NOT NULL AUTO_INCREMENT,
                `FriendlyName` longtext CHARACTER SET utf8mb4 COLLATE {MySqlCollation.Name} NULL,
                `Xml` longtext CHARACTER SET utf8mb4 COLLATE {MySqlCollation.Name} NULL,
                PRIMARY KEY (`Id`)
            ) CHARACTER SET utf8mb4;
            """,

        _ => throw new InvalidOperationException(
            $"Il provider {provider} non tiene le chiavi Data Protection nel database: " +
            $"chiamare {nameof(CreateTableSql)} solo dopo {nameof(UsesDatabaseKeyRing)}."),
    };
}
