using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Vipi.Infrastructure.Persistence;

namespace Vipi.Host;

/// <summary>
/// Persistenza delle chiavi Data Protection (usate per antiforgery, cookie auth, ecc.). STACCABILE come il
/// modulo auth. Su Render (free) il container è effimero: il key-ring di default finisce in
/// <c>/root/.aspnet/DataProtection-Keys</c> e si perde a ogni redeploy → token antiforgery invalidi e utenti
/// sloggati. Qui le chiavi vanno su un DbContext dedicato, così vivono su Neon (persistente) e sopravvivono
/// ai redeploy. Attivo SOLO quando <c>Persistence:Provider=Postgres</c>: in dev (SQLite) resta il file-store
/// di default, adeguato a una singola macchina. Il context è separato da <see cref="VipiDbContext"/> per non
/// toccarne modello e migrazioni; la sua unica tabella si crea via EnsureCreated all'avvio.
/// </summary>
public static class VipiDataProtection
{
    /// <summary>Se il provider è Postgres, registra il key-store su DB. Ritorna <c>true</c> se attivato.</summary>
    public static bool AddVipiDataProtection(this WebApplicationBuilder builder)
    {
        var provider = PersistenceProviderResolver.Resolve(
            builder.Configuration[PersistenceProviderResolver.ProviderConfigKey]);
        if (provider != PersistenceProvider.Postgres) return false;

        var connectionString = builder.Configuration.GetConnectionString("Vipi");
        if (string.IsNullOrWhiteSpace(connectionString)) return false;

        // Stessa resilienza di VipiDbContext (vedi DependencyInjection): Neon sospende il compute e chiude le
        // connessioni idle, quindi la prima query dopo l'inattività fallisce "transient". Senza retry qui, un
        // transient sul key-ring si propaga a tutto ciò che passa da Data Protection — antiforgery, cookie di
        // auth e lo state OIDC — e il login muore con «Correlation failed» invece di riprovare. Copre anche
        // UseVipiDataProtection: ExecuteSqlRaw passa dall'execution strategy, quindi il CREATE TABLE all'avvio
        // non fa più fallire il boot se Neon si sta risvegliando.
        builder.Services.AddDbContext<DataProtectionKeysDbContext>(o => o
            .UseNpgsql(connectionString, npg => npg
                .EnableRetryOnFailure(maxRetryCount: 5, maxRetryDelay: TimeSpan.FromSeconds(10), errorCodesToAdd: null)));

        // SetApplicationName fissa il discriminatore di scopo: instanze/redeploy diversi condividono lo stesso
        // key-ring (senza, ogni deploy userebbe uno scopo diverso e i vecchi token resterebbero comunque invalidi).
        builder.Services.AddDataProtection()
            .SetApplicationName("vIPI")
            .PersistKeysToDbContext<DataProtectionKeysDbContext>();

        return true;
    }

    /// <summary>Crea la tabella delle chiavi se manca (idempotente). No-op se il modulo non è attivo.</summary>
    public static WebApplication UseVipiDataProtection(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var ctx = scope.ServiceProvider.GetService<DataProtectionKeysDbContext>();
        if (ctx is null) return app;

        // NON EnsureCreated(): controlla l'esistenza del *database* (già creato da VipiDbContext), quindi non
        // creerebbe mai la tabella su un DB condiviso esistente → 42P01. Creo direttamente la tabella con lo
        // schema atteso da EntityFrameworkCoreXmlRepository (Id identità, FriendlyName, Xml). Idempotente;
        // Postgres-only (il context è registrato solo su questo ramo).
        ctx.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS "DataProtectionKeys" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FriendlyName" text NULL,
                "Xml" text NULL
            );
            """);
        return app;
    }
}

/// <summary>Context dedicato al solo key-ring Data Protection (tabella <c>DataProtectionKeys</c>).</summary>
public sealed class DataProtectionKeysDbContext : DbContext, IDataProtectionKeyContext
{
    public DataProtectionKeysDbContext(DbContextOptions<DataProtectionKeysDbContext> options) : base(options) { }

    public DbSet<DataProtectionKey> DataProtectionKeys => Set<DataProtectionKey>();
}
