using System.Text;

namespace Vipi.Sectorfile.Models;

/// <summary>
/// Output of every parser: the parsed domain objects plus a complete chunk representation
/// of the file. The chunk list is the sole input to the saver — it preserves every byte of
/// the original file that is not explicitly modified (NFR-04).
///
/// Implemented as a record so callers can clone with <c>with</c> while preserving
/// <see cref="Encoding"/> / <see cref="HasByteOrderMark"/>.
/// </summary>
public sealed record ParseResult<T>(
    IReadOnlyList<T> Records,
    IReadOnlyList<FileChunk<T>> Chunks,
    Encoding Encoding,
    bool HasByteOrderMark)
{
    /// <summary>
    /// Line terminator of the original file ("\r\n" or "\n"). The FileSaverOrchestrator joins
    /// output lines with this so an unmodified save is byte-for-byte identical (NFR-04).
    /// Defaults to CRLF.
    /// </summary>
    public string NewLine { get; init; } = "\r\n";

    /// <summary>True if the original file ended with a trailing newline. Preserved on write (NFR-04).</summary>
    public bool HasFinalNewLine { get; init; } = true;
}

/// <summary>
/// Discriminated union — every line of the file belongs to exactly one chunk.
/// Concrete kinds: <see cref="RawChunk{T}"/>, <see cref="RecordChunk{T}"/>.
/// </summary>
public abstract class FileChunk<T>;

/// <summary>
/// Lines that produce no domain object: blank lines, section headers, orphan comments,
/// deprecated sections, DUMMY terminators not part of a record body, etc.
/// </summary>
public sealed class RawChunk<T> : FileChunk<T>
{
    public RawChunk(IEnumerable<string> lines)
        => Lines = lines?.ToArray() ?? throw new ArgumentNullException(nameof(lines));

    public string[] Lines { get; }
}

/// <summary>One domain object plus the lines it was parsed from.</summary>
public sealed class RecordChunk<T> : FileChunk<T>
{
    public RecordChunk(T record, IEnumerable<string> rawLines, bool hasMarkers, IEnumerable<string>? leadingComments = null)
    {
        Record = record;
        RawLines = rawLines?.ToArray() ?? throw new ArgumentNullException(nameof(rawLines));
        HasMarkers = hasMarkers;
        LeadingComments = leadingComments?.ToArray() ?? Array.Empty<string>();
    }

    public T Record { get; }

    /// <summary>
    /// Comment lines (starting with //) immediately preceding the record. Preserved verbatim
    /// when the record is not dirty; editable by the user or auto-generated by the application.
    /// </summary>
    public string[] LeadingComments { get; set; }

    /// <summary>
    /// Original lines of the record itself, excluding LeadingComments and //Start//End markers.
    /// Used verbatim when the record is not dirty.
    /// </summary>
    public string[] RawLines { get; }

    /// <summary>
    /// True if the file already contained //Start / //End markers around this record
    /// (i.e. it was previously saved by this application). False for original Aurora files.
    /// </summary>
    public bool HasMarkers { get; }
}
