// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vipi.Infrastructure.Persistence;

#nullable disable

namespace Vipi.Infrastructure.MySqlMigrations.Migrations
{
    [DbContext(typeof(VipiDbContext))]
    [Migration("20260805190445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vipi.Domain.Entities.Acc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("CountryPrefix")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsForeign")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMilitary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Accs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AccSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AtcCallsign")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ComposePosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Frequency")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LowerLimit")
                        .HasColumnType("int");

                    b.Property<string>("MiddleIdentifier")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ParentCallsign")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Position")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("ComposePosition")
                        .IsUnique();

                    b.HasIndex("ParentCallsign");

                    b.ToTable("AccSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("int");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ParentCallsign")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("TransitionAltitudeFt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.HasIndex("ParentCallsign");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportExtraSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportExtraSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportFrequencyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("LabelOverride")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SourceSectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceSectorId");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportFrequencyLinks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("AppProcedures")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("Bearing")
                        .HasColumnType("int");

                    b.Property<string>("Circling")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("LdaM")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("LengthM")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Patterns")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ToraM")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportRunways");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunwayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("ArrRunways")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("DateFromMonthDay")
                        .HasColumnType("int");

                    b.Property<string>("DateParity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("DateToMonthDay")
                        .HasColumnType("int");

                    b.Property<int?>("DaysOfWeekMask")
                        .HasColumnType("int");

                    b.Property<string>("DepRunways")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("MaxCrosswindKt")
                        .HasColumnType("int");

                    b.Property<int>("MaxTailwindKt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("TimeFromLocalMin")
                        .HasColumnType("int");

                    b.Property<int?>("TimeToLocalMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportRunwayRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("AtcCallsign")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ComposePosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Frequency")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAccApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShapeSynthetic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimitsFromSource")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LowerLimit")
                        .HasColumnType("int");

                    b.Property<string>("MiddleIdentifier")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ParentCallsign")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Position")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccCode");

                    b.HasIndex("AirportIcao");

                    b.HasIndex("ComposePosition")
                        .IsUnique();

                    b.HasIndex("ParentCallsign");

                    b.ToTable("AirportSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Cat")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Condition")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("ForcePublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InitialClimb")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("InitialClimbByApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsImported")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("NeedsFixReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Runway")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("SourceAiracCycle")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("StableKey")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Transition")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Wtc")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportSids");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportTransitionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("QnhFrom")
                        .HasColumnType("int");

                    b.Property<int?>("QnhTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportTransitionLevels");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("BodyJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("CalloutKind")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("CollapsedByDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("FromSectorId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int?>("SharedBlockId")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("ToSectorId")
                        .HasColumnType("int");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("FromSectorId");

                    b.HasIndex("ScopeSectorId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SharedBlockId");

                    b.HasIndex("ToSectorId");

                    b.HasIndex("DocumentVersionId", "SectionId", "Order");

                    b.ToTable("ContentBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AiracCycle")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("Ident");

                    b.ToTable("CoordinationPoints");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ReleaseAiracCycle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("ReleaseEffectiveUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetKey", "ReleaseEffectiveUtc");

                    b.HasIndex("TargetType", "TargetKey", "VersionNumber");

                    b.ToTable("DocReleases");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("LastUpdatedAiracCycle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockExpiresUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LockedByName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NeedsReviewUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SectorId");

                    b.ToTable("DocumentParties");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FreqLinksJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("FreqOrderJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("HiddenAorSectorsJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("HiddenFrequenciesJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("HiddenSectionsJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentProfiles");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BeforeParentBody")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<string>("RenderMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Frozen")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("DocumentVersionId", "ParentSectionId", "Order");

                    b.ToTable("DocumentSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("UserId", "AccId")
                        .IsUnique();

                    b.ToTable("EditGrants");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditResourceLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LockExpiresUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LockedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LockedByName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("LockedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("ResourceKey")
                        .IsUnique();

                    b.ToTable("EditResourceLocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditorTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("AssigneeUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("DueAiracCycle")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("TargetKey")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("TargetLabel")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("TargetType")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("Status");

                    b.ToTable("EditorTasks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ImportPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("ImportRunways")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ImportSectors")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ImportSids")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ImportTransitionAltitude")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ImportPolicies");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ImportState", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastError")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("LastSuccessUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Category");

                    b.ToTable("ImportStates");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ByteSize")
                        .HasColumnType("int");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.NavReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Ident", "AiracCycle");

                    b.ToTable("NavReferences");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.NeighbourCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdjacentForeignCallsigns")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("AdjacentHomeCallsigns")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("AdjacentSectorCount")
                        .HasColumnType("int");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ForeignAccCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ForeignAccName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ForeignRootCallsign")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("HomeAccCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<double?>("MinDistanceNm")
                        .HasColumnType("double");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("VloaDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeAccCode", "ForeignAccCode")
                        .IsUnique();

                    b.ToTable("NeighbourCandidates");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("AirportIcao")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("ApproachKind")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("CoverageOrder")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFrequency")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProjected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("ParentSectorId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("AirportId");

                    b.HasIndex("Callsign")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParentSectorId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SharedBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("BodyJson")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SharedBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SidFixAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FixName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("SidFixAliases");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SpecialArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActivationDetails")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IvaoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("MaximumAlt")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAlt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("Range")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("IvaoId")
                        .IsUnique();

                    b.ToTable("SpecialAreas");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.StaffMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("AtcRating")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastVerifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StaffPositionsCsv")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("UserId");

                    b.HasIndex("IsActive");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.TransferFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("AirportIcao")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("AirportName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("OwningSectorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("OwningSectorId");

                    b.HasIndex("AccId", "OwningSectorId", "Order");

                    b.ToTable("TransferFlows");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.TransferPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConditionAreaLabel")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ConditionCustomLabel")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ConditionLabel")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("ConditionRefId")
                        .HasColumnType("int");

                    b.Property<string>("Cop")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("FlowId")
                        .HasColumnType("int");

                    b.Property<string>("LevelConstraint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("LevelSpecial")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("LevelUnit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int?>("LevelValue")
                        .HasColumnType("int");

                    b.Property<int?>("NextSectorId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("VerticalState")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("NextSectorId");

                    b.HasIndex("FlowId", "Order");

                    b.ToTable("TransferPoints");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("AccId", "Priority");

                    b.ToTable("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("MinimaFt")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("VectoringMinimaRows");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("SourceAiracCycle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<string>("SourceCommit")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.HasKey("Id");

                    b.HasIndex("ScopeSectorId");

                    b.ToTable("VectoringMinimaSets");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AccSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("AccSectors")
                        .HasForeignKey("CenterId")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("Airports")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportExtraSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("ExtraSections")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportFrequencyLink", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("FrequencyLinks")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "SourceSector")
                        .WithMany()
                        .HasForeignKey("SourceSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("SourceSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunway", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Runways")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunwayRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("RunwayRules")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("AirportSectors")
                        .HasForeignKey("AirportIcao")
                        .HasPrincipalKey("Icao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSid", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Sids")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportTransitionLevel", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("TransitionLevels")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Blocks")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "FromSector")
                        .WithMany()
                        .HasForeignKey("FromSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "Section")
                        .WithMany("Blocks")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.SharedBlock", "SharedBlock")
                        .WithMany()
                        .HasForeignKey("SharedBlockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ToSector")
                        .WithMany()
                        .HasForeignKey("ToSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("FromSector");

                    b.Navigation("ScopeSector");

                    b.Navigation("Section");

                    b.Navigation("SharedBlock");

                    b.Navigation("ToSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Parties")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentProfile", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "ParentSection")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditGrant", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("Sectors")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Sectors")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Sectors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ParentSector")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Acc");

                    b.Navigation("Airport");

                    b.Navigation("Document");

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SpecialArea", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.TransferFlow", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "OwningSector")
                        .WithMany()
                        .HasForeignKey("OwningSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");

                    b.Navigation("OwningSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.TransferPoint", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.TransferFlow", "Flow")
                        .WithMany("Points")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "NextSector")
                        .WithMany()
                        .HasForeignKey("NextSectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("NextSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("UnificationRules")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaRow", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.VectoringMinimaSet", "Set")
                        .WithMany("Rows")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ScopeSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Acc", b =>
                {
                    b.Navigation("AccSectors");

                    b.Navigation("Airports");

                    b.Navigation("Sectors");

                    b.Navigation("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.Navigation("AirportSectors");

                    b.Navigation("ExtraSections");

                    b.Navigation("FrequencyLinks");

                    b.Navigation("RunwayRules");

                    b.Navigation("Runways");

                    b.Navigation("Sectors");

                    b.Navigation("Sids");

                    b.Navigation("TransitionLevels");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("Sectors");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.TransferFlow", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
