using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Vipi.Infrastructure.Persistence;

namespace Vipi.DbSeed;

/// <summary>
/// Variante di <see cref="VipiDbContext"/> per il seed: forza ogni PK a <see cref="ValueGenerated.Never"/>
/// così EF include il valore della chiave nell'INSERT (preservando gli ID della sorgente SQLite). Le colonne
/// identità Postgres create da EnsureCreated sono GENERATED BY DEFAULT → l'insert esplicito è ammesso.
/// Nessuno schema si crea da qui: la destinazione esiste già (EnsureCreated del deploy).
/// </summary>
public sealed class SeedDbContext : VipiDbContext
{
    public SeedDbContext(DbContextOptions<VipiDbContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder b)
    {
        base.OnModelCreating(b);
        foreach (var entity in b.Model.GetEntityTypes())
            foreach (var key in entity.GetKeys())
                foreach (var prop in key.Properties)
                    prop.ValueGenerated = ValueGenerated.Never;
    }
}
