// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vipi.Infrastructure.Persistence;

#nullable disable

namespace Vipi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VipiDbContext))]
    [Migration("20260826083102_RiassuntoMensileAtc")]
    partial class RiassuntoMensileAtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Vipi.Domain.Entities.Acc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForeign")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMilitary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpecialAreasEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Accs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AccSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtcCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposePosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("ComposePosition")
                        .IsUnique();

                    b.HasIndex("ParentCallsign");

                    b.ToTable("AccSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementAirport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Order");

                    b.ToTable("AgreementAirports");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementClause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommsHandoffKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unspecified");

                    b.Property<string>("CommsHandoffLabel")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionAreaLabel")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionCustomLabel")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionLabel")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConditionRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cops")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HandoffKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unspecified");

                    b.Property<string>("HandoffLabel")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("HandoffLevelConstraint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AtOrAbove");

                    b.Property<string>("HandoffLevelUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Fl");

                    b.Property<int?>("HandoffLevelValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGroupWide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelConstraint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LevelSpecial")
                        .HasColumnType("TEXT");

                    b.Property<string>("LevelUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeedConstraint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unspecified");

                    b.Property<int?>("SpeedValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VariantGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerticalState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Order");

                    b.HasIndex("SectionId", "VariantGroup", "Order");

                    b.ToTable("AgreementClauses");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgreementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgreementId", "Order");

                    b.HasIndex("AgreementId", "Kind", "Direction");

                    b.ToTable("AgreementSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElevationFt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMilitaryPresence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iata")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMilitaryOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCallsign")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransitionAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.HasIndex("ParentCallsign");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportDayTraffic", b =>
                {
                    b.Property<string>("Icao")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<int>("AtcMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoveredMovements")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inbound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outbound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Overflight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Icao", "Day");

                    b.HasIndex("Day");

                    b.ToTable("AirportDayTraffic");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportExtraSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportExtraSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportFrequencyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelOverride")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSectorId");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportFrequencyLinks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppProcedures")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Bearing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Circling")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LdaM")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LengthM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Patterns")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToraM")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportRunways");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunwayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrRunways")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DateFromMonthDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateParity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DateToMonthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DaysOfWeekMask")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepRunways")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxCrosswindKt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTailwindKt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeFromLocalMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeToLocalMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportRunwayRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposePosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAccApp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShapeSynthetic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LimitsFromSource")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccCode");

                    b.HasIndex("AirportIcao");

                    b.HasIndex("ComposePosition")
                        .IsUnique();

                    b.HasIndex("ParentCallsign");

                    b.ToTable("AirportSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForcePublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialClimb")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InitialClimbByApp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsFixReview")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Runway")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAiracCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportSids");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportTransitionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QnhFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QnhTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportTransitionLevels");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcMonthRollup", b =>
                {
                    b.Property<DateTime>("Month")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("BusyMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sessions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrafficMoved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrafficSeen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Month", "UserId", "Callsign");

                    b.HasIndex("Month");

                    b.HasIndex("UserId");

                    b.ToTable("AtcMonthRollups");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcSession", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrafficCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TrafficFilledUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrafficMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("ShiftKey");

                    b.HasIndex("StartUtc");

                    b.HasIndex("Callsign", "StartUtc");

                    b.HasIndex("UserId", "StartUtc");

                    b.ToTable("AtcSessions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcSessionRunway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arrival")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "FromUtc");

                    b.ToTable("AtcSessionRunways");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcSessionTraffic", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PilotCallsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("LegOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftIcao")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrIcao")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepIcao")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntryAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstPhase")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FlightPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HandoffFromSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HandoffToSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObservationGap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPhase")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PilotUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SawAirborne")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SawMovement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeenMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "PilotCallsign", "LegOrdinal");

                    b.HasIndex("PilotCallsign");

                    b.ToTable("AtcSessionTraffic");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalloutKind")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CollapsedByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SharedBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromSectorId");

                    b.HasIndex("ScopeSectorId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SharedBlockId");

                    b.HasIndex("ToSectorId");

                    b.HasIndex("DocumentVersionId", "SectionId", "Order");

                    b.ToTable("ContentBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerAccId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SideASectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SideBSectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SideBSectorId");

                    b.HasIndex("OwnerAccId", "Order");

                    b.HasIndex("SideASectorId", "SideBSectorId")
                        .IsUnique();

                    b.ToTable("CoordinationAgreements");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ident");

                    b.ToTable("CoordinationPoints");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseAiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseEffectiveUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetKey", "ReleaseEffectiveUtc");

                    b.HasIndex("TargetType", "TargetKey", "VersionNumber");

                    b.ToTable("DocReleases");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedAiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedByName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClearedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClearedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublicNow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaisedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonArgsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClearedUtc", "RaisedUtc");

                    b.HasIndex("DocumentId", "Kind", "SourceKey", "ClearedUtc")
                        .IsUnique();

                    b.ToTable("DocumentImpacts");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SectorId");

                    b.ToTable("DocumentParties");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FreqLinksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreqOrderJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiddenAorSectorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiddenFrequenciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiddenSectionsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentProfiles");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BeforeParentBody")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LeadSentence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Frozen");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("DocumentVersionId", "ParentSectionId", "Order");

                    b.ToTable("DocumentSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("UserId", "AccId")
                        .IsUnique();

                    b.ToTable("EditGrants");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditResourceLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LockExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedByName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LockedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceKey")
                        .IsUnique();

                    b.ToTable("EditResourceLocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditorTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssigneeUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueAiracCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("Status");

                    b.ToTable("EditorTasks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ImportPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportAtcSessions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImportRunways")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportSectors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportSids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImportSpecialAreas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImportTransitionAltitude")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportPolicies");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ImportState", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSuccessUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrevSuccessUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Category");

                    b.ToTable("ImportStates");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.NavReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Ident", "AiracCycle");

                    b.ToTable("NavReferences");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.NeighbourCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjacentForeignCallsigns")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjacentHomeCallsigns")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdjacentSectorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignAccCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignAccName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignRootCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAccCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MinDistanceNm")
                        .HasColumnType("REAL");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VloaDocumentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeAccCode", "ForeignAccCode")
                        .IsUnique();

                    b.ToTable("NeighbourCandidates");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportIcao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApproachKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverageOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultFrequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProjected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("AirportId");

                    b.HasIndex("Callsign")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParentSectorId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SharedBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SharedBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SidFixAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("SidFixAliases");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SpecialArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IvaoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumAlt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumAlt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IvaoId")
                        .IsUnique();

                    b.ToTable("SpecialAreas");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SpecialAreaCenter", b =>
                {
                    b.Property<string>("IvaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("IvaoId", "CenterId");

                    b.HasIndex("CenterId");

                    b.ToTable("SpecialAreaCenters");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.StaffMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtcRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffPositionsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("IsActive");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.StatsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublicLeaderboard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatsSettings");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccId", "Priority");

                    b.ToTable("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AccSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("AccSectors")
                        .HasForeignKey("CenterId")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementAirport", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.AgreementSection", "Section")
                        .WithMany("Airports")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementClause", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.AgreementSection", "Section")
                        .WithMany("Clauses")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.CoordinationAgreement", "Agreement")
                        .WithMany("Sections")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agreement");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("Airports")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithOne("Airport")
                        .HasForeignKey("Vipi.Domain.Entities.Airport", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Acc");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportExtraSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("ExtraSections")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportFrequencyLink", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("FrequencyLinks")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "SourceSector")
                        .WithMany()
                        .HasForeignKey("SourceSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("SourceSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunway", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Runways")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunwayRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("RunwayRules")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("AirportSectors")
                        .HasForeignKey("AirportIcao")
                        .HasPrincipalKey("Icao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSid", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Sids")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportTransitionLevel", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("TransitionLevels")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcSessionRunway", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.AtcSession", "Session")
                        .WithMany("Runways")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcSessionTraffic", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.AtcSession", "Session")
                        .WithMany("Traffic")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Blocks")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "FromSector")
                        .WithMany()
                        .HasForeignKey("FromSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "Section")
                        .WithMany("Blocks")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.SharedBlock", "SharedBlock")
                        .WithMany()
                        .HasForeignKey("SharedBlockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ToSector")
                        .WithMany()
                        .HasForeignKey("ToSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("FromSector");

                    b.Navigation("ScopeSector");

                    b.Navigation("Section");

                    b.Navigation("SharedBlock");

                    b.Navigation("ToSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationAgreement", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "OwnerAcc")
                        .WithMany()
                        .HasForeignKey("OwnerAccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "SideASector")
                        .WithMany()
                        .HasForeignKey("SideASectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "SideBSector")
                        .WithMany()
                        .HasForeignKey("SideBSectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerAcc");

                    b.Navigation("SideASector");

                    b.Navigation("SideBSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentImpact", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Parties")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentProfile", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "ParentSection")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditGrant", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("Sectors")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Sectors")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Sectors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ParentSector")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Acc");

                    b.Navigation("Airport");

                    b.Navigation("Document");

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SpecialAreaCenter", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.SpecialArea", "Area")
                        .WithMany("Centers")
                        .HasForeignKey("IvaoId")
                        .HasPrincipalKey("IvaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("UnificationRules")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Acc", b =>
                {
                    b.Navigation("AccSectors");

                    b.Navigation("Airports");

                    b.Navigation("Sectors");

                    b.Navigation("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AgreementSection", b =>
                {
                    b.Navigation("Airports");

                    b.Navigation("Clauses");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.Navigation("AirportSectors");

                    b.Navigation("ExtraSections");

                    b.Navigation("FrequencyLinks");

                    b.Navigation("RunwayRules");

                    b.Navigation("Runways");

                    b.Navigation("Sectors");

                    b.Navigation("Sids");

                    b.Navigation("TransitionLevels");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AtcSession", b =>
                {
                    b.Navigation("Runways");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationAgreement", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Navigation("Airport");

                    b.Navigation("Parties");

                    b.Navigation("Sectors");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SpecialArea", b =>
                {
                    b.Navigation("Centers");
                });
#pragma warning restore 612, 618
        }
    }
}
