// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vipi.Infrastructure.Persistence;

#nullable disable

namespace Vipi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VipiDbContext))]
    [Migration("20260628140454_SimplifyDataModel")]
    partial class SimplifyDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Vipi.Domain.Entities.Acc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMilitary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Accs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AccSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposePosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("ComposePosition")
                        .IsUnique();

                    b.ToTable("AccSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransitionAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportFrequencyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelOverride")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceFrequencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceFrequencyId");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportFrequencyLinks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppProcedures")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Bearing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Circling")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LdaM")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LengthM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Patterns")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToraM")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportRunways");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunwayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrRunways")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateParity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DaysOfWeekMask")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepRunways")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Rain")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Snow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeFromUtcMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeToUtcMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WindDirFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WindDirTo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WindSpeedMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WindSpeedMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportRunwayRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposePosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionMapPolygon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccCode");

                    b.HasIndex("AirportIcao");

                    b.HasIndex("ComposePosition")
                        .IsUnique();

                    b.ToTable("AirportSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialClimb")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Runway")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportSids");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportTransitionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QnhFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QnhTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportId", "Order");

                    b.ToTable("AirportTransitionLevels");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalloutKind")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CollapsedByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SharedBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromSectorId");

                    b.HasIndex("ScopeSectorId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SharedBlockId");

                    b.HasIndex("ToSectorId");

                    b.HasIndex("DocumentVersionId", "SectionId", "Order");

                    b.ToTable("ContentBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ident");

                    b.ToTable("CoordinationPoints");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedAiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedByName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SectorId");

                    b.ToTable("DocumentParties");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("SectionKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("DocumentVersionId", "ParentSectionId", "Order");

                    b.ToTable("DocumentSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("UserId", "AccId")
                        .IsUnique();

                    b.ToTable("EditGrants");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequencyMhz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ImportPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportRunways")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportSectors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportTransitionAltitude")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportPolicies");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.NavReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Ident", "AiracCycle");

                    b.ToTable("NavReferences");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportIcao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApproachKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverageOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultFrequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeaturedRank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccId");

                    b.HasIndex("AirportId");

                    b.HasIndex("Callsign")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParentSectorId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SharedBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SharedBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.StaffMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtcRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffPositionsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("IsActive");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlRule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerChainJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("StandardFallback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccId", "RelationKey", "Phase", "Order");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AccId", "Priority");

                    b.ToTable("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimaFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("VectoringMinimaRows");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeSectorId");

                    b.ToTable("VectoringMinimaSets");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AccSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("AccSectors")
                        .HasForeignKey("CenterId")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("Airports")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportFrequencyLink", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("FrequencyLinks")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Frequency", "SourceFrequency")
                        .WithMany()
                        .HasForeignKey("SourceFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("SourceFrequency");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunway", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Runways")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportRunwayRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("RunwayRules")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("AirportSectors")
                        .HasForeignKey("AirportIcao")
                        .HasPrincipalKey("Icao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportSid", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Sids")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.AirportTransitionLevel", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("TransitionLevels")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Blocks")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "FromSector")
                        .WithMany()
                        .HasForeignKey("FromSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "Section")
                        .WithMany("Blocks")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.SharedBlock", "SharedBlock")
                        .WithMany()
                        .HasForeignKey("SharedBlockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ToSector")
                        .WithMany()
                        .HasForeignKey("ToSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("FromSector");

                    b.Navigation("ScopeSector");

                    b.Navigation("Section");

                    b.Navigation("SharedBlock");

                    b.Navigation("ToSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Parties")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "ParentSection")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.EditGrant", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Frequency", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Sector", "Sector")
                        .WithMany("Frequencies")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("Sectors")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Airport", "Airport")
                        .WithMany("Sectors")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Sectors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ParentSector")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Acc");

                    b.Navigation("Airport");

                    b.Navigation("Document");

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany()
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Acc", "Acc")
                        .WithMany("UnificationRules")
                        .HasForeignKey("AccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaRow", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.VectoringMinimaSet", "Set")
                        .WithMany("Rows")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ScopeSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Acc", b =>
                {
                    b.Navigation("AccSectors");

                    b.Navigation("Airports");

                    b.Navigation("Sectors");

                    b.Navigation("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Airport", b =>
                {
                    b.Navigation("AirportSectors");

                    b.Navigation("FrequencyLinks");

                    b.Navigation("RunwayRules");

                    b.Navigation("Runways");

                    b.Navigation("Sectors");

                    b.Navigation("Sids");

                    b.Navigation("TransitionLevels");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("Sectors");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Frequencies");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
