// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vipi.Infrastructure.Persistence;

#nullable disable

namespace Vipi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VipiDbContext))]
    [Migration("20260620084314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Vipi.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalloutKind")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CollapsedByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SharedBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromSectorId");

                    b.HasIndex("ScopeSectorId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SharedBlockId");

                    b.HasIndex("ToSectorId");

                    b.HasIndex("DocumentVersionId", "SectionId", "Order");

                    b.ToTable("ContentBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.CoordinationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ident");

                    b.ToTable("CoordinationPoints");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedAiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<int?>("ScopePositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("ScopePositionId");

                    b.HasIndex("Type", "ScopePositionId", "Status");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("PositionId");

                    b.ToTable("DocumentParties");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("DocumentVersionId", "ParentSectionId", "Order");

                    b.ToTable("DocumentSections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByVid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Fir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Firs");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequencyMhz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.HierarchyRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentPositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildPositionId");

                    b.HasIndex("ParentPositionId", "ChildPositionId")
                        .IsUnique();

                    b.ToTable("HierarchyRelations");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.NavReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Ident", "AiracCycle");

                    b.ToTable("NavReferences");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApproachKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverageOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultFrequency")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeometryRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Callsign")
                        .IsUnique();

                    b.HasIndex("FirId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.PositionSector", b =>
                {
                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PositionId", "SectorId");

                    b.HasIndex("SectorId");

                    b.ToTable("PositionSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GeometryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.HasIndex("FirId", "Key")
                        .IsUnique();

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SectorGeometry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCallsign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SectorGeometries");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.SharedBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SharedBlocks");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FirId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("FirId", "Priority");

                    b.ToTable("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimaFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("VectoringMinimaRows");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScopeSectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAiracCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeSectorId");

                    b.ToTable("VectoringMinimaSets");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Blocks")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "FromSector")
                        .WithMany()
                        .HasForeignKey("FromSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "Section")
                        .WithMany("Blocks")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.SharedBlock", "SharedBlock")
                        .WithMany()
                        .HasForeignKey("SharedBlockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vipi.Domain.Entities.Sector", "ToSector")
                        .WithMany()
                        .HasForeignKey("ToSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("FromSector");

                    b.Navigation("ScopeSector");

                    b.Navigation("Section");

                    b.Navigation("SharedBlock");

                    b.Navigation("ToSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Vipi.Domain.Entities.Position", "ScopePosition")
                        .WithMany()
                        .HasForeignKey("ScopePositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");

                    b.Navigation("ScopePosition");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentParty", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Parties")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.DocumentSection", "ParentSection")
                        .WithMany("Children")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentVersion");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Frequency", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Position", "Position")
                        .WithMany("Frequencies")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.HierarchyRelation", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Position", "ChildPosition")
                        .WithMany()
                        .HasForeignKey("ChildPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Position", "ParentPosition")
                        .WithMany()
                        .HasForeignKey("ParentPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildPosition");

                    b.Navigation("ParentPosition");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Position", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Fir", "Fir")
                        .WithMany("Positions")
                        .HasForeignKey("FirId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fir");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.PositionSector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Position", "Position")
                        .WithMany("PositionSectors")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Fir", "Fir")
                        .WithMany("Sectors")
                        .HasForeignKey("FirId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vipi.Domain.Entities.SectorGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fir");

                    b.Navigation("Geometry");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.UnificationRule", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Fir", "Fir")
                        .WithMany("UnificationRules")
                        .HasForeignKey("FirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fir");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaRow", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.VectoringMinimaSet", "Set")
                        .WithMany("Rows")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.HasOne("Vipi.Domain.Entities.Sector", "ScopeSector")
                        .WithMany()
                        .HasForeignKey("ScopeSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ScopeSector");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Document", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentSection", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.DocumentVersion", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Fir", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Sectors");

                    b.Navigation("UnificationRules");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.Position", b =>
                {
                    b.Navigation("Frequencies");

                    b.Navigation("PositionSectors");
                });

            modelBuilder.Entity("Vipi.Domain.Entities.VectoringMinimaSet", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
