namespace Vipi.Sectorfile.Models;

/// <summary>Airport classification carried in the airport metafile (default <see cref="Standard"/>).</summary>
public enum AirportType { Standard, Fss }

/// <summary>
/// Per-airport metafile (<c>_meta/airports/&lt;ICAO&gt;.asdx</c>, JSON UTF-8 no BOM — ARCHITECTURE §6).
/// Lists every source file for the airport (global first, then FIR-specific). When absent it is
/// auto-generated by naming convention + content scan; <see cref="SchemaVersion"/> drives migration.
/// <para>Note: <see cref="AirportType"/> is an additive field beyond the ARCHITECTURE §6 JSON sketch,
/// required by TEST_MATRIX §34.2/§34.7/§34.8; it defaults to <see cref="AirportType.Standard"/>.</para>
/// </summary>
public sealed class AirportMetafile
{
    public const int CurrentSchemaVersion = 1;

    /// <summary>Defaults to 0 so a missing JSON field is detected as legacy and migrated (ARCHITECTURE §6).</summary>
    public int SchemaVersion { get; set; }

    public string Type { get; set; } = "airport";   // JSON discriminator
    public string Icao { get; set; } = string.Empty;
    public AirportType AirportType { get; set; } = AirportType.Standard;
    public string PrimaryFir { get; set; } = string.Empty;
    public Dictionary<string, List<string>> Files { get; set; } = new();
}

/// <summary>
/// Per-FIR (sector) metafile (<c>_meta/sectors/&lt;CODE&gt;.asdx</c> — ARCHITECTURE §6). <see cref="Name"/>
/// is auto-derived from the first <c>//…</c> comment of the FIR <c>.frq</c>; the file lists follow the
/// naming conventions. <see cref="SectorAssociations"/> maps an AtcPosition code to a StaticBoundaryGroup name.
/// </summary>
public sealed class SectorMetafile
{
    public const int CurrentSchemaVersion = 1;

    /// <summary>Defaults to 0 so a missing JSON field is detected as legacy and migrated.</summary>
    public int SchemaVersion { get; set; }

    public string Type { get; set; } = "fir";   // JSON discriminator
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public Dictionary<string, List<string>> Files { get; set; } = new();
    public Dictionary<string, string> SectorAssociations { get; set; } = new();
}
